/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ContactDetailsResponse {
    'synced': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "synced",
            "baseName": "synced",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContactDetailsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
