/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FriendRequestItem {
    'id': string;
    'userName': string;
    'firstName': string;
    'lastName': string;
    'profile': string;
    'userType': string;
    'connectionCount': number;
    'followerCount': number;
    'followingCount': number;
    'following': Array<string>;
    'followers': Array<string>;
    'friendRequestRecord': Array<string>;
    'friendRequests': string;
    'storeName': string;
    'storeLogo': string;
    'location': Array<string>;
    'currency': string;
    'followRequestId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "string",
            "format": ""
        },
        {
            "name": "userType",
            "baseName": "userType",
            "type": "string",
            "format": ""
        },
        {
            "name": "connectionCount",
            "baseName": "connectionCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "followerCount",
            "baseName": "followerCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "followingCount",
            "baseName": "followingCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "following",
            "baseName": "following",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "followers",
            "baseName": "followers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "friendRequestRecord",
            "baseName": "friendRequestRecord",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "friendRequests",
            "baseName": "friendRequests",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeName",
            "baseName": "storeName",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeLogo",
            "baseName": "storeLogo",
            "type": "string",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "followRequestId",
            "baseName": "followRequestId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FriendRequestItem.attributeTypeMap;
    }

    public constructor() {
    }
}

