/**
 * Bookish API
 * The bookish API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UserFollowers {
    'followers': Array<string>;
    'following': Array<string>;
    'followStatus': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "followers",
            "baseName": "followers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "following",
            "baseName": "following",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "followStatus",
            "baseName": "followStatus",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserFollowers.attributeTypeMap;
    }

    public constructor() {
    }
}
